### PR TITLE
User can minify CSS files and see the size of the generated files.

### PR DESCRIPTION
**Pull request by Paari**
Let me know if you have anything specific to add to this?

### CODE REVIEW

**Comment by vikrantnegi** [comment]
ahh. Thanks, @Paari for the pull request. Will have to test this request before merging so that it doesn't break anything.

**Comment by Paari** [comment]
Oki doki 🤘🏼 
It should work fine, just run npm install/yarn install and in the readme, I have mentioned the command for the minification in that. The existing commands will work the same, it will not affect your existing commands. 

Let me know if you run into any issues!

**Comment by vikrantnegi** [comment]
@Paari Can you add the source-maps to your `minify-css` task. 

Also, I'm thinking is it necessary to have watch command for the `minify-css` task? 
As this task will be a secondary task that one will run only when they want to have final minify CSS. It is just like image task that one will run once in a while.

What are your thoughts on this?

**Comment by Paari** [comment]
Hey I have added source map, check and let me know if that is how you wanted it?

And it is fine to have direct minify option, just in case someone wants it, **we can remove it**, if you feel like.

**Comment by vikrantnegi** [comment]
Thanks @Paari .

**Pull request merged**
